### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by rckortiz** [rckortiz/assignments#31]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by rckortiz** [comment]
I'm including two versions of my resumé here for feedback. One is on the longer side and goes more into detail with my work experience and the other is a single page that omits a lot of info (work experience specifically) Hoping for feedback on this and what I can change to improve it. 
[Rick's Resume.pdf](https://github.com/rckortiz/assignments/files/3655730/Rick.s.Resume.pdf)
[Ricks_Resume copy(updated).pdf](https://github.com/rckortiz/assignments/files/3655736/Ricks_Resume.copy.updated.pdf)

**Comment by ktrammell95** [comment]
Rick,

I didn't know if I liked the Question headers at first but it started to grow on me because it is different. See how the recruiters feel about it also.

Your Skills section is taking up too much space. This about using columns to bring it up to give you more room for other stuff on that page.
![Screen Shot 2019-09-26 at 10 43 48 AM](https://user-images.githubusercontent.com/10440779/65698614-cc38ff80-e04a-11e9-9bce-019029f9fdd5.png)

For What I've Done, I would almost add another header to break out projects vs work experience. They almost flow into each other too much. 

Also, start with your most recent job and work backward.
![Screen Shot 2019-09-26 at 10 46 10 AM](https://user-images.githubusercontent.com/10440779/65698742-00acbb80-e04b-11e9-8aaf-e19b4a5ef567.png)

Keep an eye out for inconsistent spacing
![Screen Shot 2019-09-26 at 10 47 29 AM](https://user-images.githubusercontent.com/10440779/65698814-1c17c680-e04b-11e9-8b08-7b5e8f8e1cfa.png)

I like these but they feel lost at the bottom, I would almost say construct more of a letter feel and send that as an additional document or figure out how to get more of these details higher up so they are seen and not just a random page at the end.
![Screen Shot 2019-09-26 at 10 49 38 AM](https://user-images.githubusercontent.com/10440779/65699049-7e70c700-e04b-11e9-8ffe-797d6ce01379.png)
